//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiInventory.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbinventoryEntities : DbContext
    {
        public dbinventoryEntities()
            : base("name=dbinventoryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cabinet> Cabinet { get; set; }
        public virtual DbSet<CabinetInventoryObject> CabinetInventoryObject { get; set; }
        public virtual DbSet<CurrentStatus> CurrentStatus { get; set; }
        public virtual DbSet<Employe> Employe { get; set; }
        public virtual DbSet<History> History { get; set; }
        public virtual DbSet<InventoryObject> InventoryObject { get; set; }
        public virtual DbSet<InventoryObjectDetails> InventoryObjectDetails { get; set; }
        public virtual DbSet<InventoryObjectInentoryObjectDetails> InventoryObjectInentoryObjectDetails { get; set; }
        public virtual DbSet<Invoce> Invoce { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<SubType> SubType { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Type> Type { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
